### ISSUE TITLE
Overriding  table template is my application bundle

### ISSUE THREAD

**Issue by alex-barylski** [ekyna/TableBundle#4]
Hi again,

Following your example - I extended the table template with the following:

```

{% extends 'EkynaTableBundle:table.html.twig' %}

{% block table_head %}
<thead>
    <tr>
        <th>
          THIS WHOLE COLUMN OVERRIDE
        </th>
    </tr>
</thead>
{% endblock table_head %}
```

but this resulted in an error:

> Unable to find template "EkynaTableBundle:table.html.twig" in MyProjectBundle:Table:table.html.twig at line 1.

So I moved the table.html.twig one folder deep - so:

`ekyna\table-bundle\Ekyna\Bundle\TableBundle\Resources\views\Default\table.html.twig`

Then I updated the twig reference like so:

`{% extends 'EkynaTableBundle:Default:table.html.twig' %}`

This seems to have corrected the issue (assuming it's a convention thing - all my generated bundles have this folder structure minimum it seems???

Am I doing something wrong?

**Comment by ekyna** [comment]
You should never change anything in the vendor directory as this is third party libraries.

You just forgot a colon in the template name :

```
{% extends 'EkynaTableBundle::table.html.twig' %}
```

not 

```
 {% extends 'EkynaTableBundle:table.html.twig' %}
```

**Comment by alex-barylski** [comment]
Figured it out - your bundle only provides a base template (other examples I looked at used overrides I am guessing).

http://symfony.com/doc/current/book/templating.html#referencing-templates-in-a-bundle

Changed the top of the code above to:

{% extends 'EkynaTableBundle::table.html.twig' %}

Voila!!!
